<?php
/**
 * Register ACF Fields programmatically.
 *
 * @package lemon-concentrate
 */

/**
 * Register ACF fields for Product Categories programmatically.
 */
function lemon_concentrate_register_taxonomy_fields() {
	if ( function_exists( 'acf_add_local_field_group' ) ) {
		acf_add_local_field_group( array(
			'key' => 'group_product_category_extras',
			'title' => __( 'Category Settings', 'lemon-concentrate' ),
			'fields' => array(
				array(
					'key' => 'field_product_category_icon',
					'label' => __( 'Icon / Image', 'lemon-concentrate' ),
					'name' => 'icon',
					'type' => 'image',
					'instructions' => __( 'Upload an image or icon for this category.', 'lemon-concentrate' ),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array(
					'key' => 'field_product_category_color',
					'label' => __( 'Category Color', 'lemon-concentrate' ),
					'name' => 'category_color',
					'type' => 'color_picker',
					'instructions' => __( 'Override the default dynamic color for this category.', 'lemon-concentrate' ),
				),
				array(
					'key' => 'field_product_category_hero_background_image',
					'label' => __( 'Hero Background Image', 'lemon-concentrate' ),
					'name' => 'hero_background_image',
					'type' => 'image',
					'instructions' => __( 'Upload a background image for the category header.', 'lemon-concentrate' ),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_product_category_hero_image',
					'label' => __( 'Hero Image', 'lemon-concentrate' ),
					'name' => 'hero_image',
					'type' => 'image',
					'instructions' => __( 'Upload an image for the category content area.', 'lemon-concentrate' ),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'taxonomy',
						'operator' => '==',
						'value' => 'product_category',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		) );
	}
}
add_action( 'acf/init', 'lemon_concentrate_register_taxonomy_fields' );

/**
 * Register Options Page.
 */
function lemon_concentrate_register_options_page() {
	if ( function_exists( 'acf_add_options_page' ) ) {
		acf_add_options_page( array(
			'page_title' => 'Settings',
			'menu_slug'  => 'settings',
			'position'   => '2.1',
			'redirect'   => false,
			'icon_url'   => 'dashicons-admin-tools',
		) );
	}
}
add_action( 'acf/init', 'lemon_concentrate_register_options_page' );

add_action( 'acf/init', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_6979f0f1dceb0',
		'title' => 'Breadcrumbs',
		'fields' => array(
			array(
				'key' => 'field_6979f0f2916e1',
				'label' => '',
				'name' => '',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'lemon-concentrate/breadcrumbs',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_698091aba12c4',
		'title' => 'Global Settings',
		'fields' => array(
			array(
				'key' => 'field_698091aba2ae0',
				'label' => 'Testimonials',
				'name' => 'testimonials',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => array(
					array(
						'quote' => 'This is a sample testimonial quote.',
					),
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_698091b7a2ae1',
						'label' => 'Quote',
						'name' => 'quote',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_698091aba2ae0',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_697333eadc5b5',
		'title' => 'Nav Bar',
		'fields' => array(
			array(
				'key' => 'field_697333ebd3ed4',
				'label' => 'Nav Bar',
				'name' => 'nav_bar',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Main Navigation',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/lemon-nav-fixed',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6979e23692bf7',
		'title' => 'Product',
		'fields' => array(
			array(
				'key' => 'field_product_settings_tab',
				'label' => 'Settings',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_product_color_override',
				'label' => 'Product Color Override',
				'name' => 'product_color_override',
				'type' => 'color_picker',
				'instructions' => 'Override the default category color for this product.',
				'return_format' => 'string',
			),
			array(
				'key' => 'field_6982f7a7e4e3d',
				'label' => 'Hero',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6980f8d86e7ec',
				'label' => 'Hero Image',
				'name' => 'hero_image',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_hero_bullets',
				'label' => 'Hero Bullets',
				'name' => 'hero_bullets',
				'type' => 'repeater',
				'instructions' => 'Add bullet points to display in the hero section.',
				'layout' => 'table',
				'button_label' => 'Add Bullet',
				'sub_fields' => array(
					array(
						'key' => 'field_hero_bullet_text',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
					),
				),
				'default_value' => array(
					array( 'text' => 'Premium Quality' ),
					array( 'text' => '100% Organic' ),
					array( 'text' => 'Sustainably Sourced' ),
				),
			),
			array(
				'key' => 'field_6982f7bde4e3e',
				'label' => 'Techical Specifications',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_6982f24957239',
				'label' => 'Technical Specifications',
				'name' => 'technical_specifications',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_6982f2955723a',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					'default_value' => 'Technical Specifications',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_6982f2a05723b',
						'label' => 'Introduction',
						'name' => 'introduction',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					'default_value' => 'Detailed information about the product specifications and requirements.',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_6982f2b95723c',
						'label' => 'List',
						'name' => 'list',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => array(
							array(
								'icon' => 'tag',
								'text' => 'Product: apple juice concentrate 70º Brix (AJC)',
							),
							array(
								'icon' => 'droplet',
								'text' => 'Brix (°Bx): 69.0 – 71.0',
							),
							array(
								'icon' => 'droplet',
								'text' => 'Acidity (as malic acid): 1.6 – 2.4 g/100 mL',
							),
							array(
								'icon' => 'material',
								'text' => 'Formats: aseptic drums, frozen drums, IBC containers, flexitanks, Bag-in-Box',
							),
							array(
								'icon' => 'temperature',
								'text' => 'Storage: frozen at –18 ºC for frozen formats, ambient for aseptic formats',
							),
							array(
								'icon' => 'weight',
								'text' => 'MOQ: 5–10 MT per reference',
							),
						),
						'layout' => 'table',
						'button_label' => 'Add Item',
						'sub_fields' => array(
							array(
								'key' => 'field_tech_spec_icon',
								'label' => 'Icon',
								'name' => 'icon',
								'type' => 'select',
								'choices' => array(
									'weight'      => 'Weight',
									'dimensions'  => 'Dimensions',
									'material'    => 'Material',
									'temperature' => 'Temperature',
									'warranty'    => 'Warranty',
									'tag'         => 'Tag',
									'droplet'     => 'Droplet',
								),
								'return_format' => 'value',
							),
							array(
								'key' => 'field_tech_spec_text',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'text',
							),
						),
					),
					array(
						'key' => 'field_698321ec1a49b',
						'label' => 'PDF Download',
						'name' => 'url',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_6982f7f1e4e3f',
				'label' => 'Sections',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69806c798ea2c',
				'label' => 'Sections',
				'name' => 'sections',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => array(
					array(
						'order' => 1,
						'title' => 'Sample Section',
						'text' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
					),
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_69806d47b1ae6',
						'label' => 'Order',
						'name' => 'order',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'allow_in_bindings' => 1,
						'ui_on_text' => 'Left',
						'ui_off_text' => 'Right',
						'ui' => 1,
						'parent_repeater' => 'field_69806c798ea2c',
					),
					array(
						'key' => 'field_69806c7e8ea2d',
						'label' => 'Title',
						'name' => 'title',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_69806c798ea2c',
					),
					array(
						'key' => 'field_69806c998ea2e',
						'label' => 'Image',
						'name' => 'image',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'allow_in_bindings' => 0,
						'preview_size' => 'medium',
						'parent_repeater' => 'field_69806c798ea2c',
					),
					array(
						'key' => 'field_69806d2fb1ae5',
						'label' => 'Text',
						'name' => 'text',
						'aria-label' => '',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'allow_in_bindings' => 0,
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
						'parent_repeater' => 'field_69806c798ea2c',
					),
				),
			),
			array(
				'key' => 'field_product_faq_tab',
				'label' => 'FAQ',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_69832433f6133',
				'label' => 'FAQ',
				'name' => 'faq',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => array(
					array(
						'question' => 'What is the shelf life?',
						'answer' => 'The shelf life is 24 months from the date of manufacture.',
					),
					array(
						'question' => 'Is this organic?',
						'answer' => 'Yes, our products are 100% organic certified.',
					),
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_product_faq_question',
						'label' => 'Question',
						'name' => 'question',
						'type' => 'text',
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array(
						'key' => 'field_product_faq_answer',
						'label' => 'Answer',
						'name' => 'answer',
						'type' => 'text',
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lemon_product',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'excerpt',
			1 => 'discussion',
			2 => 'comments',
			3 => 'revisions',
			4 => 'slug',
			5 => 'author',
			6 => 'format',
			7 => 'page_attributes',
			8 => 'categories',
			9 => 'tags',
			10 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 1,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_69732c9a269c4',
		'title' => 'Product Category Loop',
		'fields' => array(
			array(
				'key' => 'field_69732c9ac907c',
				'label' => 'Product Catgegories',
				'name' => 'product_categories',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'product_category',
				'add_term' => 1,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'id',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'allow_in_bindings' => 0,
				'bidirectional' => 0,
				'multiple' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_697efb02b5586',
				'label' => 'Show All Categories',
				'name' => 'show_all_categories',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'allow_in_bindings' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'lemon-concentrate/product-category-loop',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_697b3c47b816b',
		'title' => 'Ticker',
		'fields' => array(
			array(
				'key' => 'field_697b3c48a8fd4',
				'label' => 'Ticker Item',
				'name' => 'ticker_items',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => array(
					array(
						'question' => 'What is the shelf life?',
						'answer' => 'The shelf life is 24 months from the date of manufacture.',
					),
					array(
						'question' => 'Is this organic?',
						'answer' => 'Yes, our products are 100% organic certified.',
					),
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_697b3c54a8fd5',
						'label' => 'Ticker Item',
						'name' => 'ticker_item',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_697b3c48a8fd4',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'lemon-concentrate/ticker',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_6978fbd674ed8',
		'title' => 'FAQ',
		'fields' => array(
			array(
				'key' => 'field_6978fbd66c08c',
				'label' => 'FAQ Items',
				'name' => 'faq_items',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_6978fbf96c08d',
						'label' => 'Question',
						'name' => 'question',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6978fbd66c08c',
					),
					array(
						'key' => 'field_6978fc0b6c08e',
						'label' => 'Answer',
						'name' => 'answer',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'allow_in_bindings' => 0,
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_6978fbd66c08c',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'lemon-concentrate/faq-accordion',
				),
			),
		),
		'menu_order' => 20,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	) );

	acf_add_local_field_group( array(
		'key' => 'group_simple_menu_block',
		'title' => 'Simple Menu Block',
		'fields' => array(
			array(
				'key' => 'field_simple_menu_select',
				'label' => 'Select Menu',
				'name' => 'selected_menu',
				'type' => 'select',
				'instructions' => 'Select the menu to display.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(), // Populated via filter
				'default_value' => false,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'id',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'lemon-concentrate/simple-menu',
				),
			),
		),
	) );
} );

function lemon_concentrate_populate_menu_select( $field ) {
	$field['choices'] = array();
	$menus = wp_get_nav_menus();
	if ( $menus ) {
		foreach ( $menus as $menu ) {
			$field['choices'][ $menu->term_id ] = $menu->name;
		}
	}
	return $field;
}
add_filter( 'acf/load_field/name=selected_menu', 'lemon_concentrate_populate_menu_select' );